import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { PopUpProvider } from '../context/PopUpContext';
import { ModalProvider } from '../context/ModalContext';
import { UserProvider } from '../context/UserContext';
import { CartProvider } from '../context/CartContext'; // Import CartProvider
import SessionProviderWrapper from "./SessionProviderWrapper"; // Import the SessionProviderWrapper

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"], 
});

export const metadata = {
  title: 'Black Noise App', // Puedes cambiar esto
  description: 'Generated by create next app', // Puedes cambiar esto
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className="bg-primary text-secondary">
        <SessionProviderWrapper> {/* Wrap the entire application with SessionProviderWrapper */}
          <PopUpProvider>
            <ModalProvider>
              <UserProvider>
                <CartProvider> {/* Wrap with CartProvider */}
                  {children}
                </CartProvider>
              </UserProvider>
            </ModalProvider>
          </PopUpProvider>
        </SessionProviderWrapper>
      </body>
    </html>
  )
}
