import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { PopUpProvider } from '../context/PopUpContext';
import { ModalProvider } from '../context/ModalContext';
<<<<<<< HEAD
import { UserProvider } from '../context/UserContext';
import { CartProvider } from '../context/CartContext'; // Import CartProvider
import SessionProviderWrapper from "./SessionProviderWrapper"; // Import the SessionProviderWrapper

=======
import { CartProvider } from '../context/CartContext'; // Import CartProvider
import SessionProviderWrapper from './SessionProviderWrapper';
import { MockSessionProvider } from '@/context/MockSessionContext';
import SessionToggleButton from '@/components/common/SessionToggleButton';
import { MockDataProvider } from '@/context/MockDataContext';
import MockDataToggleButton from '@/components/common/MockDataToggleButton';
>>>>>>> e32d185aa7ca43c5c2af446b5ff65a84e8a01a7d
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
<<<<<<< HEAD
  title: 'Black Noise App', // Puedes cambiar esto
  description: 'Generated by create next app', // Puedes cambiar esto
=======
  title: 'Black Noise App',
  description: 'Generated by create next app',
>>>>>>> e32d185aa7ca43c5c2af446b5ff65a84e8a01a7d
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className="bg-primary text-secondary">
<<<<<<< HEAD
        <SessionProviderWrapper> {/* Wrap the entire application with SessionProviderWrapper */}
          <PopUpProvider>
            <ModalProvider>
              <UserProvider>
                <CartProvider> {/* Wrap with CartProvider */}
                  {children}
                </CartProvider>
              </UserProvider>
            </ModalProvider>
          </PopUpProvider>
        </SessionProviderWrapper>
=======
          <PopUpProvider>
            <ModalProvider>
                <CartProvider> {/* Aquí envuelves con CartProvider */}
                  <SessionProviderWrapper>
                    <MockSessionProvider>
                      <MockDataProvider>
                        {children}
                        {/* Mock Data Toggle Button */}
                        <div style={{ position: 'fixed', bottom: '70px', right: '20px', zIndex: 1000 }}>
                          <MockDataToggleButton />
                        </div>
                        {/* Session Toggle Button */}
                        <div style={{ position: 'fixed', bottom: '20px', right: '20px', zIndex: 1000 }}>
                          <SessionToggleButton />
                        </div>
                      </MockDataProvider>
                    </MockSessionProvider>
                  </SessionProviderWrapper>
                </CartProvider>
            </ModalProvider>
          </PopUpProvider>
>>>>>>> e32d185aa7ca43c5c2af446b5ff65a84e8a01a7d
      </body>
    </html>
  )
}
