import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { PopUpProvider } from '../context/PopUpContext';
import SessionProviderWrapper from './SessionProviderWrapper';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: 'Black Noise App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className="bg-primary text-secondary">
          <PopUpProvider>
                  <SessionProviderWrapper>
                    {children}
                  </SessionProviderWrapper>
          </PopUpProvider>
      </body>
    </html>
  )
}
