/**
 * Enumeraciones relacionadas con el modelo Pedido
 */

export const EstadoPedido = {
    PENDIENTE: 'PENDIENTE',
    EN_FABRICACION: 'EN_FABRICACION',
    LISTO: 'LISTO',
    ENVIADO: 'ENVIADO',
    ENTREGADO: 'ENTREGADO',
    CANCELADO: 'CANCELADO',
    SOLICITUD_DEVOLUCION: 'SOLICITUD_DEVOLUCION',
    DEVOLUCION_APROBADA: 'DEVOLUCION_APROBADA',
    DEVOLUCION_RECHAZADA: 'DEVOLUCION_RECHAZADA',
    DEVUELTO: 'DEVUELTO',
    SOLICITUD_CANCELACION: 'SOLICITUD_CANCELACION',
    REHACER_PEDIDO: 'REHACER_PEDIDO'
}
