export const MetodoPago = {
    EFECTIVO: 'EFECTIVO',
    TRANSFERENCIA_BANCARIA: 'TRANSFERENCIA_BANCARIA',
    TARJETA_CREDITO: 'TARJETA_CREDITO',
    TARJETA_DEBITO: 'TARJETA_DEBITO',
    NEQUI: 'NEQUI',
    DAVIPLATA: 'DAVIPLATA',
    PSE: 'PSE'
};

export default MetodoPago;
